GET {{apiUrl}}/accounts
Accept: application/json

###

POST {{apiUrl}}/accounts
Accept: application/json
Content-Type: application/json

{
  "username": "username",
  "email": "username@test.com",
  "password": "idKfA01"
}

###

GET {{apiUrl}}/accounts/2
Accept: application/json

###

PUT {{apiUrl}}/accounts/2
Accept: application/json
Content-Type: application/json

{
    "username": "username",
    "email": "username@test.com",
    "password": "idKfA__01"
}

###

DELETE {{apiUrl}}/accounts/2
Accept: application/json

###
